app:
  port: 8080

db:
  host:     "0.0.0.0"
  port:     "5432"
  user:     "postgres"
  password: "12345678"
  db_name:  "mygame"
  ssl_mode: "disable"

jwt:
  secret_key:      "1234"
  expiration_time: "24h"